src/objects/FieloELR__Course__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMSELR_ContentCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content Category</label>
        <referenceTo>FieloCMS__Category__c</referenceTo>
        <relationshipLabel>Courses (Content Category)</relationshipLabel>
        <relationshipName>ContentCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloELR__Module__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMSELR_ContentCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content Category</label>
        <referenceTo>FieloCMS__Category__c</referenceTo>
        <relationshipLabel>Content Modules</relationshipLabel>
        <relationshipName>ContentModules</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/FieloCMSELR_PostsTest.cls
@isTest
public with sharing class FieloCMSELR_PostTest{
	
	//Method that creates the Test Data with 3 Modules 'Basic'
	@testSetup static void setup(){
		MockUpFactory.InsertTestData();
	}

	@isTest static void ELRChangeModuleTest(){
		
		FieloELR__Module__c module = [SELECT Id, FieloELR__Course__c FROM FieloELR__Module__c WHERE Name = 'Basic'];
		
		FieloCMSELR_CourseService.relateToCategories(new Set<Id>{module.FieloELR__Course__c});
		
		FieloCMSELR_ModuleService.relateToCategories(new Set<Id>{module.Id});

		module = [SELECT Id, FieloCMSELR_ContentCategory__c, FieloELR__Course__c FROM FieloELR__Module__c WHERE Id =: module.Id];

		
		FieloELR__Course__c course = [SELECT Id, FieloCMSELR_ContentCategory__c FROM FieloELR__Course__c WHERE Id =:module.FieloELR__Course__c];

		FieloCMS__Post__c post = new FieloCMS__Post__c(
			Name = 'Post',
			FieloCMS__Category__c = module.FieloCMSELR_ContentCategory__c,
			FieloCMS__Content__c = 'Test'
		);

		insert post;

		post.FieloCMS__Category__c = course.FieloCMSELR_ContentCategory__c;

		String errorMsg = '';
		try{
			update post;
		}
		catch(Exception err ){
			errorMsg = err.getMessage();
		}
		System.assert(errorMsg.contains(Label.FieloCMSELR_PostCategoryReadOnly));
	
	}

	@isTest static void ELRChangeCourseTest(){
		
		FieloELR__Module__c module = [SELECT Id, FieloELR__Course__c FROM FieloELR__Module__c WHERE Name = 'Basic'];
		
		FieloCMSELR_CourseService.relateToCategories(new Set<Id>{module.FieloELR__Course__c});
		
		FieloCMSELR_ModuleService.relateToCategories(new Set<Id>{module.Id});

		module = [SELECT Id, FieloCMSELR_ContentCategory__c, FieloELR__Course__c FROM FieloELR__Module__c WHERE Id =: module.Id];

		FieloELR__Course__c course = [SELECT Id, FieloCMSELR_ContentCategory__c FROM FieloELR__Course__c WHERE Id =:module.FieloELR__Course__c];

		FieloCMS__Post__c post = new FieloCMS__Post__c(
			Name = 'Post',
			FieloCMS__Category__c = course.FieloCMSELR_ContentCategory__c,
			FieloCMS__Content__c = 'Test'
		);
		insert post;

		post.FieloCMS__Category__c = module.FieloCMSELR_ContentCategory__c;

		String errorMsg = '';
		try{
			update post;
		}
		catch(Exception err ){
			errorMsg = err.getMessage();
		}
		System.assert(errorMsg.contains(Label.FieloCMSELR_PostCategoryReadOnly));
	
	}
		

}