src/objects/FieloELR__Course__c.object
<CustomObject>
    <fields>
        <fullName>FieloELR__Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloELR__CourseStatus__c.object
<CustomObject>
    <fields>
        <fullName>FieloELR__Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>FieloELR__Course__c</referenceTo>
        <relationshipLabel>Courses Status</relationshipLabel>
        <relationshipName>CoursesStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloELR__Progress__c</fullName>
        <formula>FieloELR__ApprovedModules__c / FieloELR__Course__r.FieloELR__ActiveModules__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Progress</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Course Status</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Course Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSELR_ProgressBarCtlr.cls
public class FieloCMSELR_ProgressBarCtlr implements FieloCMS.ViewSubComponentInterface {
    public ApexPages.Component getSubComponent(FieloCMS.Field field, SObject record){
    	system.debug(field);
    	system.debug(record);
        Component.FieloCMSELR_ProgressBar progress = new Component.FieloCMSELR_ProgressBar();
        return progress;
    }

    @RemoteAction
    public static List<SObject> getCourseStatus(List<String> courseIds) {
        Id memberId = FieloCMSPLT_MemberService.getCurrentMemberId();
        List<FieloELR__CourseStatus__c> courseStatus = FieloELR.CourseService.getCourseStatus(
            new Set<String>{'FieloELR__Progress__c','FieloELR__Course__c'},
            null,
            new Set<Id>((List<Id>)courseIds),
            memberId,
            100,
            0,
            'FieloELR__Course__r.FieloELR__Order__c'
        );
        return courseStatus;
    }
}