src/objects/FieloELR__Course__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMSELR_ContentCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content Category</label>
        <referenceTo>FieloCMS__Category__c</referenceTo>
        <relationshipLabel>Courses (Content Category)</relationshipLabel>
        <relationshipName>ContentCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSELR_Courses.cls
public with sharing class FieloCMSELR_Courses {
	
	public static void onBeforeUpdate(List<FieloELR__Course__c> courses, Map<Id,FieloELR__Course__c> existingRecords){
		List<FieloCMS__Category__c> categories = new List<FieloCMS__Category__c>();
		for(FieloELR__Course__c course : courses){
			if(course.Name != existingRecords.get(course.Id).Name && course.FieloCMSELR_ContentCategory__c != null){
				categories.add(new FieloCMS__Category__c(Id = course.FieloCMSELR_ContentCategory__c, Name = course.Name));
			}
		}

		update categories;
	}

}